import Head from "next/head";
import HomeMain from "../components/Home/HomeMain";
import Footer from "../components/Layout/Footer/Footer";
import Header from "../components/Layout/Header";

export default function Home({ showHeaderUser }) {
  return (
    <>
      <Head>
        <title>Tiktok Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <HomeMain />
      <Footer />
    </>
  );
}
